### ISSUE TITLE
Rotate PI-TS35 v1.0 180°

### ISSUE THREAD

**Issue by michalfrnoch** [makerbase-mks/MKS-PI#12]
I have a problem,
the TwoTress Sapphire PRO printer has an MKS RObin TFT35 V1.0 display, it has the same proportions as the MKS Pi-TS35 V1.0, but unfortunately, the klipper screen is upside down. How to change the display orientation by 180°

**Comment by jpmimard** [comment]
Same question 👍

**Comment by jpmimard** [comment]
discord chanel seems to be closed

**Comment by nikolaigd** [comment]
Unzip and add to /boot/dtb/rockchip/
and reboot the system
[rk3328-roc-cc.zip](https://github.com/makerbase-mks/MKS-PI/files/9867132/rk3328-roc-cc.zip)

**Comment by michalfrnoch** [comment]
MEGA thanks
