### ISSUE TITLE
nmtui doesn't work and not upgrade/update anything.

### ISSUE THREAD

**Issue by acguardia** [makerbase-mks/MKS-PI#3]
mks@mkspi:~$ sudo armibian_config
sudo: armibian_config: command not found
mks@mkspi:~$ nmtui
-bash: nmtui: command not found
mks@mkspi:~$ sudo su
root@mkspi:/home/mks# cd
root@mkspi:~# nmtui
bash: nmtui: command not found
root@mkspi:~#
-------------------------------------------------
root@mkspi:~# apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libmm-glib0 libndp0 libnm0 libnma0 libopenconnect5 libpkcs11-helper1 libstoken1 libstrongswan libteamdctl0 libtomcrypt1 libtommath1 libtss2-esys0 libtss2-udev
  openconnect openvpn pptp-linux sshpass strongswan strongswan-charon strongswan-libcharon strongswan-starter vpnc vpnc-scripts xl2tpd
Use 'apt autoremove' to remove them.
The following packages will be upgraded:
  armbian-bsp-cli-renegade armbian-buster-desktop-xfce armbian-config armbian-firmware armbian-zsh exo-utils libexo-1-0 libexo-2-0 libexo-common libexo-helpers
  linux-dtb-edge-rockchip64 linux-image-edge-rockchip64 linux-libc-dev openssl tzdata
15 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 81.1 MB of archives.
After this operation, 497 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Ign:1 http://security.debian.org buster/updates/main arm64 libexo-common all 0.12.4-1+deb10u1
Err:2 http://apt.armbian.com buster/main arm64 armbian-bsp-cli-renegade arm64 22.05.3
  Could not resolve 'apt.armbian.com'
Ign:3 http://deb.debian.org/debian buster-updates/main arm64 tzdata all 2021a-0+deb10u5
Ign:4 http://security.debian.org buster/updates/main arm64 libexo-helpers all 0.12.4-1+deb10u1
Ign:5 http://apt.armbian.com buster/buster-utils arm64 armbian-buster-desktop-xfce all 22.05.3
Err:3 http://deb.debian.org/debian buster-updates/main arm64 tzdata all 2021a-0+deb10u5
  Could not resolve 'deb.debian.org'
Err:6 http://security.debian.org buster/updates/main arm64 exo-utils arm64 0.12.4-1+deb10u1
  Could not resolve 'security.debian.org'
Ign:7 http://apt.armbian.com buster/main arm64 armbian-config all 22.08.0-trunk.0038
Err:8 http://security.debian.org buster/updates/main arm64 libexo-2-0 arm64 0.12.4-1+deb10u1
  Could not resolve 'security.debian.org'
Ign:9 http://apt.armbian.com buster/main arm64 armbian-firmware all 22.08.0-trunk.0038
Err:10 http://security.debian.org buster/updates/main arm64 libexo-1-0 arm64 0.12.4-1+deb10u1
  Could not resolve 'security.debian.org'
Ign:11 http://apt.armbian.com buster/main arm64 armbian-zsh all 22.08.0-trunk.0038
Err:12 http://security.debian.org buster/updates/main arm64 openssl arm64 1.1.1n-0+deb10u3
  Could not resolve 'security.debian.org'
Err:13 http://apt.armbian.com buster/main arm64 linux-dtb-edge-rockchip64 arm64 22.05.1
  Could not resolve 'apt.armbian.com'
Err:1 http://security.debian.org buster/updates/main arm64 libexo-common all 0.12.4-1+deb10u1
  Could not resolve 'security.debian.org'
Err:14 http://apt.armbian.com buster/main arm64 linux-image-edge-rockchip64 arm64 22.05.1
  Could not resolve 'apt.armbian.com'

**Comment by makerbase-mks** [comment]
@acguardia, yes, we have uninstalled the nmtui, as it seems it has conflict with the dhcpcd. 
Without nmtui, you can also use "armbian-config->Network" to config the network.
If you still want to use nmtui, you can install it, but had better to uninstall our service:
`systemctl disable makerbase-net-mods.service`
`systemctl disable mks_wifi@wlan0`
`apt install network-manager `

I don't find the problem of "apt upgrade", maybe you can check the network?

**Comment by jakep82** [comment]
Same issue here.  I'm unable to resolve any web address making the board completely unusable.  It's also not possible to install network-manager without working host resolution, and I don't know how to solve this using armbian-config.

**Comment by makerbase-mks** [comment]
@acguardia @jakep82 ，we found it should be caused by the /etc/resolv.conf, you can try to modify the DNS on it:
`sudo sed -i "s/192.168.2.1/8.8.8.8/g" /etc/resolv.conf`

**Comment by makerbase-mks** [comment]
The new image has been updated, and fix this issue:
https://drive.google.com/file/d/1-L2HId9kAp05xsv309gqI9QjSpi3GUCU/view?usp=sharing
