### ISSUE TITLE
Mod to use LCD in Portrait mode

### ISSUE THREAD

**Issue by onolox** [makerbase-mks/MKS-PI#42]
Hi, can you plz make a mod to use the lcd in portrait mode?

It wold be so much more convenient.

**Comment by redrathnure** [comment]
@onolox , you may use [MKS-PI#how-to-modify-the-device-tree-file](https://github.com/makerbase-mks/MKS-PI#how-to-modify-the-device-tree-file) instruction to modify device tree descriptors. Just find folowwing line:
```
spi_for_lcd@0 {
  ....
  rotate = <0x10e>;
```
and replace `0x10e` to your value. `0x10e` means 270°. Probably you should try `0x0` (0°) or `0xB4` (180°) value.

**Comment by onolox** [comment]
Thanks!
