### ISSUE TITLE
What is the beep pin?

### ISSUE THREAD

**Issue by onolox** [makerbase-mks/MKS-PI#44]
Hi I have an MKS PI v1.1 with TS35.
What's the beep pin to use in klipper?

In shematics of TS35 there's an buzzer. I think almost all LCDs have an buzzer inside.

I neet to issue alerts and a music at the end of the print.

**Comment by redrathnure** [comment]
I do not see any beeper neither on LCD nor or MKS PI board. Perhaps you can grab a buzzer from old PC/motherboard and use free IO to prepare custom solution.

**Comment by onolox** [comment]
You're right, I've looking the TS35 v2, and I have the v1, that don't have it.
I will use your idea, it's good that we have some spare pins!
